version: '3.11'
services:
  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart:
      on-failure
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 3s
      retries: 3

  redis-db:
    container_name: redis-db
    image: redis:latest
    env_file:
      - .env
    ports:
      - "6379:6379"
    restart:
      on-failure

  user-balance-service:
    container_name: user-balance-service
    image: user-balance-service:latest
    env_file:
      - .env
    ports:
      - "8082:8082"
    depends_on:
      postgres-db:
        condition: service_healthy
      redis-db:
        condition: service_healthy

volumes:
  postgres-data: