server:
  forward-headers-strategy: native
  port: ${BALANCE_SERVICE_PORT}
spring:
  application:
    name: ${BALANCE_SERVICE_NAME}
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    schemas: public
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jwt:
    key: ${JWT_KEY}
    expiration: ${JWT_EXPIRATION}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
logging:
  level:
    org:
      hibernate: warn